pipeline {
    agent {
        label {
            label "slave-1"
    }
    stages {
        stage ("remove old images & containers") {
            steps {
                sh '''
                    #!/bin/bash
                    sudo service docker start
                    sudo docker container rm -f server-httpd-1
                    sudo docker system prune -af
                    sudo rm -rf *
                '''
            }
        }
        stage ("create container") {
            steps {
                sh "sudo docker run -itdp 81:80 --name server-httpd-1 httpd"
            }
        }
        stage ("deploy in docker container") {
            steps {
                sh "sudo docker cp index.html server-httpd-1:/usr/local/apache2/htdocs/"
            }
        }
    }
}
