pipeline {
    agent {
        label {
            label "slave-1"
            customWorkspace "/mnt/docker-vol/assignment-1-without-volume/24Q2"
    }
    stages {
        stage ("remove old images & containers") {
            steps {
                sh '''
                    #!/bin/bash
                    sudo service docker start
                    sudo docker container rm -f server-httpd-2
                    sudo docker system prune -af
                    sudo rm -rf *
                '''
            }
        }
        stage ("create container") {
            steps {
                sh "sudo docker run -itdp 82:80 --name server-httpd-2 httpd"
            }
        }
        stage ("git clone") {
            steps {
                sh "sudo git clone https://github.com/vinodhalsangi/Assignments-Docker.git /mnt/docker-vol/24Q2 -b 24Q2"
            }
        }
        stage ("deploy in docker container") {
            steps {
                sh "sudo docker cp /mnt/docker-vol/24Q2/index.html server-httpd-2:/usr/local/apache2/htdocs/"
            }
        }
        stage ("remove clone") {
            steps {
                sh "sudo rm -rf /mnt/docker-vol/24Q2"
            }
        }
    }
}
