pipeline {
    agent {
        label ("slave-1")
    }
    tools {
        maven "Maven-3.9.6"
    }
    stages {
        stage ("clean") {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                sh '''
                    sudo rm -rf *
                    sudo rm -rf hello-world
                    sudo docker stop $(sudo docker ps -a -q)
                    sudo docker system prune -af
                '''
                }
            }
        }
        stage ("git clone") {
            steps {
                sh "sudo git clone https://github.com/vinodhalsangi/hello-world.git"
            }
        }
        stage ("compile & package") {
            steps {
                dir ("hello-world") {
                sh '''
                    sudo chmod -R 777 .
                    mvn clean install
                '''
                }
            }
        }
        stage ("create container") {
            steps {
                sh "sudo docker run -itdp 8080:8080 --name server-hello-world tomcat:9"
            }
        }
        stage ("deploy") {
            steps {
                sh "sudo docker cp hello-world/target/hello-world-1.0-SNAPSHOT.war server-hello-world:/usr/local/tomcat/webapps"
                sh "sudo rm -rf *"
            }
        }
    }
}
