pipeline {
    agent {
        label {
            label "slave-1"
        }
    }
    stages {
        stage ("old volume, images & containers") {
            steps {
                sh '''
                    #!/bin/bash
                    sudo service docker start
                    sudo docker container rm -f server-httpd-1
                    sudo docker volume rm vol-1
                    sudo docker system prune -af
                '''
            }
        }
        stage ("create volume") {
          steps {
            sh "sudo docker volume create vol-1"
          }
        }
        stage ("create container") {
            steps {
                sh "sudo docker run -itdp 81:80 -v vol-1:/usr/local/apache2/htdocs/ --name server-httpd-1 httpd"
            }
        }
        stage ("deploy") {
            steps {
                sh "sudo mv index.html /var/lib/docker/volumes/vol-1/_data/"
            }
        }
    }
}
