pipeline {
	agent {
		label ("slave-1")
	}
	tools {
		maven-3.9.6
	}
	stages {
		stage ("clean") {
			steps {
				sh "sudo rm -rf gamepflife"
				sh "sudo docker rm -f server-tomcat-1"
				sh "sudo docker system prune -af"
			}
		}
		stage ("clone") {
			steps {
				sh "sudo git clone https://github.com/vinodhalsangi/game-of-life.git gameoflife -b master"
			}
		}
		stage ("compile & package") {
			steps {
				sh "sudo mvn clean install"
			}
		}
		stage (create container) {
			steps {
				sh "sudo docker build -t ubuntu-tomcat-1 assignment-3/."
				sh "sudo docker run -itdp 8080:8080 --name server-tomcat-1 ubuntu-tomcat-1"
			}
		}
		stage ("deploy") {
			steps {
				sh "sudo docker cp gameoflife/gameoflife-web/target/gameoflife.war server-tomcat-1:/usr/local/tomcat/webapps/"
		  }
	  }
  }
}
