pipeline {
	agent {
		label ("slave-1")
	}
	tools {
		maven "Maven-3.9.6"
	}
	stages {
		stage ("clean") {
			steps {
				catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
				sh "sudo docker rm -f server-tomcat-1"
				sh "sudo docker system prune -af"
				}
			}
		}
		stage ("clone") {
			steps {
				sh "sudo git clone https://github.com/vinodhalsangi/game-of-life.git -b master"
			}
		}
		stage ("compile & package") {
			steps {
				dir ("game-of-life") {
					sh "mvn clean install"
				}
			}
		}
		stage ("create container") {
			steps {
				dir ("game-of-life") {
					sh "sudo docker build -t ubuntu-tomcat-1 assignment-3/."
					sh "sudo docker run -itdp 8080:8080 --name server-tomcat-1 ubuntu-tomcat-1"
				}
			}
		}
		stage ("deploy") {
			steps {
				sh "sudo docker cp game-of-life/gameoflife-web/target/gameoflife.war server-tomcat-1:/usr/local/tomcat/webapps/"
				sh "sudo rm -rf *"
		  	}
	  	}
  	}
}
