pipeline {
	agent {
		label ("slave-1")
	}
	tools {
		maven "Maven-3.9.6"
	}
	stages {
		stage ("clean") {
			steps {
				catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
				sh "sudo docker rm -f server-tomcat-1"
				sh "sudo docker system prune -af"
				}
			}
		}
		stage ("clone") {
			steps {
				sh "sudo git clone https://github.com/vinodhalsangi/hello-world.git"
			}
		}
		stage ("compile & package") {
			steps {
				dir ("hello-world") {
					sh "sudo chmod -R 777 ."
					sh "mvn clean install"
				}
			}
		}
		stage ("create container") {
			steps {
				dir ("hello-world") {
					sh "sudo docker build -t ubuntu-tomcat-1 assignment-3/"
					sh "sudo docker run -itdp 8080:8080 --name server-tomcat-1 ubuntu-tomcat-1"
				}
			}
		}
		stage ("deploy") {
			steps {
				sh "sudo docker cp hello-world/target/hello-world-1.0.-SNAPSHOT.war server-tomcat-1:/usr/local/tomcat/webapps/"
				sh "sudo rm -rf *"
		  	}
	  	}
  	}
}
