pipeline {
    agent {
        label {
            label "slave-3"
            customWorkspace "/mnt/docker-vol/assignment-2-with-JNLP-connection/"
        }
    }
    tools {
        maven "Maven-3.9.6"
    }
    stages {
        stage ("clean workspace & docker") {
            steps {
                sh '''
                    sudo rm -rf *
                    sudo rm -rf /mnt/docker-vol/hello-world
                    sudo service docker start
                    sudo docker rm -f server-hello-world
                '''
            }
        }
        stage ("git clone") {
            steps {
                sh "sudo git clone https://github.com/vinodhalsangi/hello-world.git /mnt/docker-vol/hello-world"
            }
        }
        stage ("compile & package") {
            steps {
                dir ("/mnt/docker-vol/hello-world") {
                sh '''
                    sudo chmod -R 777 .
                    mvn clean install
                '''
                }
            }
        }
        stage ("create container") {
            steps {
                sh "sudo docker run -itdp 8080:8080 --name server-hello-world tomcat:9"
            }
        }
        stage ("deploy") {
            steps {
                sh "sudo docker cp /mnt/docker-vol/hello-world/target/hello-world-1.0-SNAPSHOT.war server-hello-world:/usr/local/tomcat/webapps"
                sh "sudo rm -rf hello-world"
            }
        }
    }
}
