pipeline {
    agent {
        label {
            label "slave-1"
        }
    }
    stages {
        stage ("old volume, images & containers") {
            steps {
                sh '''
                    #!/bin/bash
                    sudo service docker start
                    sudo docker container rm -f server-httpd-2
                    sudo docker system prune -af
                '''
            }
        }
        stage ("create container with deploy") {
            steps {
                sh "sudo docker run -itdp 82:80 -v $WORKSPACE:/usr/local/apache2/htdocs/ --name server-httpd-2 httpd"
            }
        }
    }
}
