pipeline {
    agent {
        label {
            label "slave-1"
            customWorkspace "/mnt/docker-vol/assignment-1-with-local-volume"
        }
    }
    stages {
        stage ("remove ws, old volume, images & containers") {
            steps {
                sh '''
                    #!/bin/bash
                    sudo service docker start
                    sudo docker container rm -f server-httpd-1
                    sudo docker system prune -af
                    sudo rm -rf 24Q1
                '''
            }
        }
        stage ("create container") {
            steps {
                sh "sudo docker run -itdp 81:80 -v /mnt/docker-vol/assignment-1-with-local-volume/24Q1:/usr/local/apache2/htdocs/ --name server-httpd-1 httpd"
            }
        }
        stage ("deploy or git clone") {
            steps {
                sh "sudo git clone https://github.com/vinodhalsangi/assignments-docker.git 24Q1 -b 24Q1"
            }
        }
    }
}
